import type { Theme, ThemeId } from './types'

export const themes: Record<ThemeId, Theme> = {
  classic: {
    id: 'classic',
    name: 'Classic Neubrutal',
    shadowOffset: '4px 4px',
    borderWidth: '3px',
    colors: {
      bg: '#FFFDF2',
      surface: '#FFFFFF',
      border: '#1A1A1A',
      text: '#1A1A1A',
      'text-muted': '#6B7280',
      primary: '#FFD600',
      'primary-hover': '#E6C200',
      secondary: '#1A1A1A',
      accent: '#FF6B35',
      success: '#22C55E',
      error: '#EF4444',
      shadow: '#1A1A1A',
    },
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber Brutal',
    shadowOffset: '4px 4px',
    borderWidth: '3px',
    colors: {
      bg: '#0A0A1A',
      surface: '#141428',
      border: '#00F0FF',
      text: '#E0E0FF',
      'text-muted': '#8888AA',
      primary: '#0066FF',
      'primary-hover': '#0052CC',
      secondary: '#00F0FF',
      accent: '#FF00FF',
      success: '#00FF88',
      error: '#FF3355',
      shadow: '#00F0FF',
    },
  },
  terminal: {
    id: 'terminal',
    name: 'Terminal',
    shadowOffset: '0 0',
    borderWidth: '2px',
    colors: {
      bg: '#0D0D0D',
      surface: '#1A1A1A',
      border: '#00FF41',
      text: '#00FF41',
      'text-muted': '#008A20',
      primary: '#00FF41',
      'primary-hover': '#00CC35',
      secondary: '#003B0D',
      accent: '#FFFFFF',
      success: '#00FF41',
      error: '#FF3355',
      shadow: '#00FF41',
    },
  },
  retro: {
    id: 'retro',
    name: 'Retro Arcade',
    shadowOffset: '5px 5px',
    borderWidth: '4px',
    colors: {
      bg: '#1A0033',
      surface: '#240044',
      border: '#FF00FF',
      text: '#FFFFFF',
      'text-muted': '#CC88FF',
      primary: '#FF00FF',
      'primary-hover': '#CC00CC',
      secondary: '#00CCFF',
      accent: '#FFD600',
      success: '#00FF88',
      error: '#FF3355',
      shadow: '#FF00FF',
    },
  },
  pastel: {
    id: 'pastel',
    name: 'Pastel Brutal',
    shadowOffset: '4px 4px',
    borderWidth: '3px',
    colors: {
      bg: '#FFF5F5',
      surface: '#FFFFFF',
      border: '#FFB3C6',
      text: '#2D1B2E',
      'text-muted': '#8B728C',
      primary: '#FFB3C6',
      'primary-hover': '#FF8FA8',
      secondary: '#B5D8EB',
      accent: '#D4B5EB',
      success: '#86E3B5',
      error: '#FF8A8A',
      shadow: '#FFB3C6',
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark Brutal',
    shadowOffset: '4px 4px',
    borderWidth: '3px',
    colors: {
      bg: '#1A1A1A',
      surface: '#2A2A2A',
      border: '#FF6B35',
      text: '#F5F5F5',
      'text-muted': '#9CA3AF',
      primary: '#FF6B35',
      'primary-hover': '#E85A26',
      secondary: '#404040',
      accent: '#FFB347',
      success: '#22C55E',
      error: '#EF4444',
      shadow: '#000000',
    },
  },
}

export const themeIds: ThemeId[] = ['classic', 'cyber', 'terminal', 'retro', 'pastel', 'dark']
